name: Build & Deploy (Vite Vue TS)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ vars.SSH_HOST }}
      SSH_PORT: ${{ vars.SSH_PORT }}
      SSH_USER: ${{ vars.SSH_USER }}
      REMOTE_PATH: ${{ vars.REMOTE_PATH }}
      VITE_UMAMI_WEBSITE_ID: ${{ vars.VITE_UMAMI_WEBSITE_ID }}
      VITE_UMAMI_SCRIPT_URL: ${{ vars.VITE_UMAMI_SCRIPT_URL }}
      VITE_UMAMI_HOST_URL: ${{ vars.VITE_UMAMI_HOST_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Build
        run: pnpm build

      - name: Sanity check CI inputs
        run: |
          set -euxo pipefail
          : "${SSH_HOST:=}"
          : "${SSH_PORT:=}"
          : "${SSH_USER:=}"
          : "${REMOTE_PATH:=}"
          : "${VITE_UMAMI_WEBSITE_ID:=}"
          : "${VITE_UMAMI_SCRIPT_URL:=}"
          : "${VITE_UMAMI_HOST_URL:=}"
          SSH_HOST="$(printf %s "$SSH_HOST" | tr -d '\r' | sed -e 's/[[:space:]]\+$//')"
          SSH_PORT="$(printf %s "$SSH_PORT" | tr -d '\r' | sed -e 's/[[:space:]]\+$//')"
          SSH_USER="$(printf %s "$SSH_USER" | tr -d '\r' | sed -e 's/[[:space:]]\+$//')"
          REMOTE_PATH="$(printf %s "$REMOTE_PATH" | tr -d '\r' | sed -e 's/[[:space:]]\+$//')"
          VITE_UMAMI_WEBSITE_ID="$(printf %s "$VITE_UMAMI_WEBSITE_ID" | tr -d '\r' | sed -e 's/[[:space:]]\+$//')"
          VITE_UMAMI_SCRIPT_URL="$(printf %s "$VITE_UMAMI_SCRIPT_URL" | tr -d '\r' | sed -e 's/[[:space:]]\+$//')"
          VITE_UMAMI_HOST_URL="$(printf %s "$VITE_UMAMI_HOST_URL" | tr -d '\r' | sed -e 's/[[:space:]]\+$//')"
          if [ -n "$SSH_PORT" ] && ! echo "$SSH_PORT" | grep -Eq '^[0-9]+$'; then echo "SSH_PORT is not numeric: '$SSH_PORT'"; exit 1; fi
          echo "SSH_HOST=${SSH_HOST:-<empty>}"
          echo "SSH_PORT=${SSH_PORT:-<empty>} (will default to 22 if empty)"
          echo "SSH_USER=${SSH_USER:-<empty>}"
          echo "REMOTE_PATH=${REMOTE_PATH:-<empty>}"
          echo "VITE_UMAMI_WEBSITE_ID=${VITE_UMAMI_WEBSITE_ID:-<empty>}"
          echo "VITE_UMAMI_SCRIPT_URL=${VITE_UMAMI_SCRIPT_URL:-<empty>}"
          echo "VITE_UMAMI_HOST_URL=${VITE_UMAMI_HOST_URL:-<empty>}"
          if [ -z "${SSH_HOST}" ] || [ -z "${SSH_USER}" ] || [ -z "${REMOTE_PATH}" ]; then
            echo "Missing required repo Variables. Set SSH_HOST, SSH_USER, REMOTE_PATH (and SSH_PORT optionally) under Settings → Secrets and variables → Actions → Variables."; exit 1; fi
          if [ -z "${VITE_UMAMI_WEBSITE_ID}" ] || [ -z "${VITE_UMAMI_SCRIPT_URL}" ]; then
            echo "Missing Umami variables. Set VITE_UMAMI_WEBSITE_ID and VITE_UMAMI_SCRIPT_URL under Settings → Secrets and variables → Actions → Variables."; exit 1; fi
          if [ -z "${SSH_PORT}" ]; then SSH_PORT=22; fi
          echo "Using SSH_PORT=$SSH_PORT"
          {
            echo "SSH_PORT=$SSH_PORT"
            echo "SSH_HOST=$SSH_HOST"
            echo "SSH_USER=$SSH_USER"
            echo "REMOTE_PATH=$REMOTE_PATH"
          } >> "$GITHUB_ENV"

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Scan host key
        run: |
          set -euxo pipefail
          install -m 700 -d ~/.ssh
          ssh-keyscan -p "${SSH_PORT}" "${SSH_HOST}" >> ~/.ssh/known_hosts

      - name: Deploy dist/ via rsync
        run: |
          set -euxo pipefail
          rsync -avz --delete \
            -e "ssh -p ${SSH_PORT}" \
            dist/ "${SSH_USER}@${SSH_HOST}:${REMOTE_PATH}/"
